Use correct Openssl inf for SBSA
microsoft/mu_tiano_platforms pull request #625
Opened 2023-07-05 16:59 UTC by kenlautner

## Description

Changed the openssl inf version used to be the full version to match expected functionality.

For each item, place an "x" in between `[` and `]` if true. Example: `[x]`.
_(you can also check items in the GitHub UI)_

- [x] Impacts functionality?
  - **Functionality** - Does the change ultimately impact how firmware functions?
  - Examples: Add a new library, publish a new PPI, update an algorithm, ...
- [x] Impacts security?
  - **Security** - Does the change have a direct security impact on an application,
    flow, or firmware?
  - Examples: Crypto algorithm change, buffer overflow fix, parameter
    validation improvement, ...
- [ ] Breaking change?
  - **Breaking change** - Will anyone consuming this change experience a break
    in build or boot behavior?
  - Examples: Add a new library class, move a module to a different repo, call
    a function in a new library class in a pre-existing module, ...
- [ ] Includes tests?
  - **Tests** - Does the change include any explicit test code?
  - Examples: Unit tests, integration tests, robot tests, ...
- [ ] Includes documentation?
  - **Documentation** - Does the change contain explicit documentation additions
    outside direct code modifications (and comments)?
  - Examples: Update readme file, add feature readme file, link to documentation
    on an a separate Web page, ...

## How This Was Tested

Passed BaseCryptLib Unit Tests.

## Integration Instructions

N/A

2023-07-05 17:29 UTC, makubacki commented
@kenlautner, I know this might be obvious, but can you list the additional functionality brought in by the change to the PR description?

2023-07-05 17:29 UTC, makubacki approved these changes

2023-07-06 00:42 UTC, TaylorBeebe requested changes
Is this change also supposed to resolve the BaseCryptLibUnitTest failure?

2023-07-06 02:00 UTC, kenlautner commented
> Is this change also supposed to res

2023-07-06 02:33 UTC, kenlautner commented
> Is this change also supposed to resolve the BaseCryptLibUnitTest failure?

Yes it is.  I see that it's still failing for Md5 Hashing which was removed from support.  We should probably discuss if we want to allow the use of Md5 hashing again or update the test.  It's legacy so we should probably add support in special cases such as this.

2023-07-06 02:33 UTC, kuqin12 approved these changes

2023-07-06 02:36 UTC, kuqin12 commented
> > Is this change also supposed to resolve the BaseCryptLibUnitTest failure?
> 
> Yes it is. I see that it's still failing for Md5 Hashing which was removed from support. We should probably discuss if we want to allow the use of Md5 hashing again or update the test. It's legacy so we should probably add support in special cases such as this.

So Q35 is not failing this test? Is it because Q35 disabled the deprecated test, or because it is also failing but still in grace period?

2023-07-06 16:27 UTC, kenlautner commented
> > > Is this change also supposed to resolve the BaseCryptLibUnitTest failure?
> > 
> > 
> > Yes it is. I see that it's still failing for Md5 Hashing which was removed from support. We should probably discuss if we want to allow the use of Md5 hashing again or update the test. It's legacy so we should probably add support in special cases such as this.
> 
> So Q35 is not failing this test? Is it because Q35 disabled the deprecated test, or because it is also failing but still in grace period?

Q35 doesn't use MD5 and it is disabled by default in MU.  SBSA enables it by including NetworkBuildOptions.dsc.inc and NETWORK_ISCSI_ENABLE is TRUE.

2023-07-07 18:22 UTC, TaylorBeebe approved these changes

2023-07-07 19:35 UTC, merged